version: "3.7"

services:
  zennit_terraform:
    build:
      context: ./
      dockerfile: Dockerfile
    image: royalsaltmerchant/zennit:latest
    ports:
      - "80:80"
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    env_file: .flaskenv