version: "3.7"

services:
  zennit:
    build:
      context: ./
    expose:
      - 5000
    ports:
      - 5000:5000
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1