"""empty message

Revision ID: 13498fbd02de
Revises: cf4f9e5a74cd
Create Date: 2021-03-10 15:45:48.250883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13498fbd02de'
down_revision = 'cf4f9e5a74cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
