"""empty message

Revision ID: 5512d9ac4868
Revises: ce0515fbec88
Create Date: 2021-03-11 22:43:10.241902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5512d9ac4868'
down_revision = 'ce0515fbec88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislike', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dislike', 'user', ['user_id'], ['id'])
    op.add_column('like', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_column('like', 'user_id')
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.drop_column('dislike', 'user_id')
    # ### end Alembic commands ###
