"""empty message

Revision ID: 964fcc18682d
Revises: 5512d9ac4868
Create Date: 2021-03-15 16:33:58.608179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964fcc18682d'
down_revision = '5512d9ac4868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dislike', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dislike', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
